### PR TITLE
Trade Republic German language parser

### PR DESCRIPTION
**Pull request by mbks**
Hi!

Thank you for the cool project. 
I've attempted to add a parser for Trade Republic documents that works for German users. For buy orders  it works fine for me (see the respective test cases), but for sell orders and dividends I faced some issues as sell does not seem to be implemented in the common parser yet and dividends are strangely structured in the German TR. I've added the (anonymized) files and commented test cases for these in the unit tests, so please have a look :)
I personally would be fine with only having buy order imports for now.

Thanks

### CODE REVIEW

**Comment by VibeNL** [comment]
Thank you for your contribution, good to hear you think it is a cool project.

Will have a look at it as soon as I'm able 😇

**Comment by VibeNL** [comment]
@mbks , for an initial version it looks fine. Let's merge it and i'll have a crack at the sell and dividends eventually 😄 

For the sells and dividends, could you create an issue so we do not lose track 👼

**Comment by mbks** [comment]
Cool, thanks for having a look :smiley:
I've created two issues for the mentioned problems: #314 and #315 
I will have another look at those as well when I have the time  :grin:

**Review by VibeNL — APPROVED** [review]

**Comment by VibeNL** [comment]
@mbks It has been merged, and thank you for contributing 😄

**Pull request merged**
